DROP TABLE IF EXISTS 'PERSON';

CREATE TABLE 'PERSON'(
	'Person_Name' VARCHAR(250) NOT NULL,
	'Person_Age' INT NOT NULL,
	'Person_Height' FLOAT(5) NOT NULL,
	'Person_Bold' BOOL NOT NULL,
	PRIMARY KEY (Person_Name));

DROP TABLE IF EXISTS 'SPEAKER';

CREATE TABLE 'SPEAKER'(
	'Speaker_Model' VARCHAR(250) NOT NULL,
	'Speaker_Power' FLOAT(5) NOT NULL,
	'Speaker_NumOfSpeakers' INT NOT NULL,
	PRIMARY KEY (Speaker_Model),
	FOREIGN KEY (Car_Plate) REFERENCES CAR(Car_Plate),
	FOREIGN KEY (Person_Name) REFERENCES PERSON(Person_Name));

DROP TABLE IF EXISTS 'CAR';

CREATE TABLE 'CAR'(
	'Car_NumOfWheels' INT NOT NULL,
	'Car_Brand' VARCHAR(250) NOT NULL,
	'Car_Plate' VARCHAR(250) NOT NULL,
	PRIMARY KEY (Car_Plate),
	FOREIGN KEY (Person_Name) REFERENCES PERSON(Person_Name));

DROP TABLE IF EXISTS 'PLANE';

CREATE TABLE 'PLANE'(
	'Plane_Height' FLOAT(5) NOT NULL,
	'Plane_Private' BOOL NOT NULL,
	'Plane_Model' VARCHAR(250) NOT NULL,
	'Plane_NumOfPeople' INT NOT NULL,
	PRIMARY KEY (Plane_Model),
	FOREIGN KEY (Speaker_Model) REFERENCES SPEAKER(Speaker_Model),
	FOREIGN KEY (Person_Name) REFERENCES PERSON(Person_Name));

DROP TABLE IF EXISTS 'PENE';

CREATE TABLE 'PENE'(
	'Pene_Width' FLOAT(5) NOT NULL,
	'Pene_Black' BOOL NOT NULL,
	'Pene_Name' VARCHAR(250) NOT NULL,
	PRIMARY KEY (Pene_Name),
	FOREIGN KEY (Person_Name) REFERENCES PERSON(Person_Name));

